spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/cwm0103/config-repo
          username: cwm0103
          password: cwm550408am
          basedir: F:\java_springboot\SpringCloud\configfile
    #配置bus消息总线
    bus:
      enabled: true
  rabbitmq:
#    addresses: 192.168.5.200:5672 #添加队列地址
    host:  192.168.5.200
    port: 5672
    username: guest
    password: guest
eureka:
  client:
    service-url:
      defaultZone: http://192.168.5.201:8761/eureka/

#management:
#  endpoint:
#    bus-env:
#      enabled: true
#    bus-refresh:
#      enabled: true
management:
  endpoint:
    bus-refresh:
      enabled: true
  endpoints:
    web:
      exposure:
        include: bus-refresh

