eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ #http://admin:123456@192.168.5.200:8761/eureka/ #http://192.168.5.200:8761/eureka/
spring:
  application:
    name: product
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/springCloud?characterEncoding=utf-8&serverTimezone=UTC
    password: root
    username: root
  jpa:
    show-sql: true
  rabbitmq:
    host: 192.168.5.200 #注册rabbitmq 地址
    port: 5672
    username: guest
    password: guest

  zipkin:
    base-url:  http://192.168.5.200:9411
    sender:
      type: web
  sleuth:
    annotation:
      enabled: true
    sampler:
      probability: 1
      rate: 1000
  cloud:
#    stream:
#      binders:
#        input:
#          content-type: application/json # 设置消息类型，本次为对象json，如果是文本则设置“text/plain”

#    stream:
#      bindings:
#        inputProduct:
#          group: abc1
#          destination: cwmtest
#          content-type: application/json
    stream:
      bindings:
        inputOrder:
#          group: abc1
          destination: order
          content-type: application/json
#redis 的连接地址
#  redis:
#    database: 0
#    host: 192.168.5.6
#    lettuce:
#      pool:
#        max-active: 8
#        max-wait: 1ms
#        max-idle: 8
#        min-idle: 0
#      shutdown-timeout: 100ms

#          #消息分区 开启
#          consumer:
#            partitioned: true
#      instance-count: 1   #消息分区 数量2
#      instance-index: 0   #指定那个通到

server:
  port: 8081

feign:
  hystrix:
    enabled: true

logging:
  level:
    org.springframework.cloud.openfeign: debug




