spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/springCloud?characterEncoding=utf-8&serverTimezone=UTC
    password: root
    username: root
  jpa:
    show-sql: true
#  cloud:
#    config:
#      discovery:
#        enabled: true
#        service-id: CONFIG
#      profile: dev
#      label: master
    stream:
      bindings:
        outputProduct:
          destination: cwmtest
          content-type: application/json
          # 生产者开启分区支持
          producer:
            partitionKeyExpression: payload
            partitionCount: 1


  rabbitmq:
    host: 192.168.5.200 #注册rabbitmq 地址
    port: 5672
    username: guest
    password: guest
  zipkin:
    base-url:  http://192.168.5.200:9411
    sender:
      type: web
  sleuth:
    annotation:
      enabled: true
    sampler:
      probability: 1
      rate: 1000

#      uri: http://localhost:8080/  #不配置这个会报以下错误
#order - was unable to refresh its cache! status = Cannot execute request on any known server


# 这个不写到这里会报 Could not locate configserver via discovery  这个错误
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ #http://admin:123456@192.168.5.200:8761/eureka/ #http://192.168.5.201:8761/eureka/

# Feign 本身支持Hystrix，不再需要引入相关的jar  Feign 本身支持Hystrix，不再需要引入相关的jar
feign:
  hystrix:
    enabled: true

logging:
  level:
    org.springframework.cloud.openfeign: debug







